# Generated by Django 5.2.1 on 2025-05-30 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_landlord',
            field=models.BooleanField(default=False),
        ),
    ]
