# Generated by Django 5.2.1 on 2025-06-03 10:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0002_advertisement_created_at'),
        ('ads_feedback', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='feedback',
            constraint=models.UniqueConstraint(fields=('rentee', 'advertisement'), name='unique_rentee_advertisement', violation_error_message='Only one feedback per property per rentee'),
        ),
    ]
